In [1]:
# Matrix addition and subtraction in Python.
import numpy as np

A = np.matrix([[50, 40], [10, 10]])  # Matrix A(morning)
B = np.matrix([[30, 100], [20, 15]])  # Matrix B(night)
A + B

matrix([[ 80, 140],
        [ 30,  25]])

In [ ]:
# Find the real multiple of the matrix
import numpy as np

A = np.matrix([[80, 140], [30, 25]])  # Matrix A
0.8 * A

In [6]:
# Let's perform matrix multiplication
import numpy as np

A = np.matrix([[1, 3], [2, 1]])  # Matrix A
B = np.matrix([[150, 250], [130, 230]])  # Matrix B
A * B

[[1 3]
 [2 1]]
[[1 3]
 [2 1]]


In [7]:
# Multiplication of l x m matrix and m x n matrix
import numpy as np

A = np.matrix([[1, 3], [2, 1]])  # Matrix A(2 x 2)
B = np.matrix([[145], [72]])  # Matrix B(2 x 1)
# Matrix x unit matrix is calculated
import numpy as np

A = np.matrix([[1, 3], [2, 1]])  # Matrix A
E = np.matrix([[1, 0], [0, 1]])  # Unit matrix E
print(A * E)
print(E * A)

[[1 3]
 [2 1]]
[[1 3]
 [2 1]]


In [11]:
# Find the inverse matrix
import numpy as np
A = np.matrix([[5, 3], [2, 1]]) # Matrix A
B = np.linalg.inv(A) # Find the inverse matrix(B)
print(B)
(A * B).astype(np.int64)

[[-1.  3.]
 [ 2. -5.]]


matrix([[1, 0],
        [0, 0]])